### ISSUE TITLE
Errors compiling minify js

### ISSUE THREAD

**Issue by claudchan** [PretorDH/Dragon#6]
Hi,
I trying to minify the scripts using closure compiler https://closure-compiler.appspot.com
and have errors: 

Number of errors: 2
JSC_CANNOT_CONVERT: This code cannot be converted from ES6. ES5 getters/setters (consider using --language_out=ES5) at line 31 character 17
                set option(o) {
                 ^
JSC_CANNOT_CONVERT: This code cannot be converted from ES6. ES5 getters/setters (consider using --language_out=ES5) at line 37 character 17
                get option() {
                 ^

Could you make a min version into the master?

Thanks.

**Comment by PretorDH** [comment]
Mini versions created....
